# Development Environment
development:
  gems : ['aws-sdk']
  aws_access_key : 'AKIAJQ4I32FNR26CB3OQ'
  aws_secret_key : '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'
  
  
# Test Environment
test:
  gems : ['aws-sdk']
  aws_access_key : 'AKIAJQ4I32FNR26CB3OQ'
  aws_secret_key : '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'
   
   
   
   
  
# Production Environment
production:
  gems : ['aws-sdk']
  aws_access_key : 'AKIAJQ4I32FNR26CB3OQ'
  aws_secret_key : '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'


