# Development Environment
development:
  aws_access_key : 'AKIAJQ4I32FNR26CB3OQ'
  aws_secret_key : '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'
  elb_name : 'GSB'
  
  
# Test Environment
test:
  aws_access_key : 'AKIAJQ4I32FNR26CB3OQ'
  aws_secret_key : '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'
  elb_name : 'GSB'
   
   
   
   
  
# Production Environment
production:
  aws_access_key : 'AKIAJQ4I32FNR26CB3OQ'
  aws_secret_key : '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'
  elb_name : 'GSB'

