# set runtime environment
environment : 'development'

# required gems
gems:
  development:
    gems : ['aws-sdk']
    enabled : true
  
  production : 
    gems : ['aws-sdk']
    enabled : true
  

# aws elements
aws:
  development:
    aws_access_key : 'AKIAJQ4I32FNR26CB3OQ'
    aws_secret_key : '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'
    enabled : true
  
  production:
    aws_access_key : 'AKIAJQ4I32FNR26CB3OQ'
    aws_secret_key : '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'
    enabled : true
